export const categories = [
  'AI Agents & Infrastructure',
  'SEO & AI Visibility',
  'Marketing & Advertising',
  'Crypto, Web3 & Investing',
  'Developer Tools',
  'Business, Finance & Legal',
  'Security, Privacy & Compliance',
  'Health, Fitness & Wellness',
  'Social Media & Creator Tools',
  'Leaderboards & Attention Markets',
  'Hiring, Jobs & Careers',
  'Education & Learning',
  'Agencies, Studios & Services',
  'Ecommerce & Retail',
  'Domains & Web Assets',
  'Games & Entertainment',
  'People & Profiles',
  'Productivity & Personal Tools',
  'Design & Creative',
  'Writing & Content',
  'Directories, Launch & Discovery',
  'AI Media Generation',
  'Audio, Voice & Podcasting',
  'Sales & Lead Generation',
  'Travel, Local & Lifestyle',
  'Real Estate & Property',
  'Media & News',
  'Other',
];
